create database oyo_hotels;
use oyo_hotels;
select * from oyo_details;
select * from city_details;

-- Number of cities included in the data set and the number of hotels taken into account
select distinct (city) from city_details;
select count(distinct(city)) as Number_of_cities from city_details;
select count(distinct(hotel_id)) as Number_of_hotels from oyo_details;

-- Number of hotels in different cities 
select A.City, count(distinct(B.hotel_id)) from city_details A 
inner join oyo_details B on A.Hotel_id = B.hotel_id group by A.City order by 2 desc;

-- Average Amount in different cities 
select A.City, avg(B.amount) from city_details A 
inner join oyo_details B on A.Hotel_id = B.hotel_id group by A.City order by 2 desc;

-- Calculate the cancellation rate 
select count(status) from oyo_details where status = 'Cancelled';
select count(status) from oyo_details;
select (95300/2889) as Overall_Cancellation_rate from oyo_details;


-- Bookings done in different months in different cities 
select A.City, count(B.date_of_booking) from city_details A 
inner join oyo_details B on A.Hotel_id = B.hotel_id group by A.City order by 2 desc;

-- Net revenue generated by each city
select A.City, sum(B.amount) from city_details A 
inner join oyo_details B on A.Hotel_id = B.hotel_id group by A.City order by 2 desc;

-- Total Gross Revenue generated
select sum(amount) as Total_Revenue_Generated from oyo_details;





